### ISSUE TITLE
Encoders don't fit through top plate

### ISSUE THREAD

**Issue by coolavery** [josefadamcik/SofleKeyboard#182] opened 2023-08-10 17:15 UTC
**Kind of issue?**
Assembly

**Which Board?**
Original

**Which Board Revision?**
Original = 2.0 

**What steps have you taken**
* [x] I have searched the Issues page
* [x] I have read the documentation 

**What is the issue?**

Hi, I ran into an issue with the v2 board. Seems to be the same as #118 - the encoders don't fit through the top plate.

The reason I'm opening an issue here is that I bought the encoders from [the AliExpress listing](https://www.aliexpress.com/item/4000891003225.html) linked [on the sourcing parts page](https://josefadamcik.github.io/SofleKeyboard/sourcing_parts.html).

I'm not sure if that's intended for a different board variant, or maybe the listing has been updated to a different part since then, but the widest part of the encoder I got is about 13.7 mm wide. The cutout is about 12.6 mm wide, which seems to match the Gerber files, so I don't think it's a manufacturing issue.

Some careful filing of the PCB should fix it (as mentioned in #118), but it would be great to get some clarification on if there's an exact part that fits better for future builds.

Thanks for creating this project, it's been a super smooth build otherwise! :heart:

**Comment by DaneEvans** [comment] 2024-03-12 02:53
Ali components are not exact. That listing doesn't even include the base dimensions at the moment - only the length. 

Short of only specifying reputable vendors (and getting complaints about the cost), all you can do is order a couple of different lots from different ali vendors and hope for the best. 

Closing a duplicate of #118

**Closed by DaneEvans** 2024-03-12 02:53 UTC
Labels: Assistance
